services:
  postgres:
    image: postgis/postgis:15-3.4
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d app"]
      interval: 10s
      timeout: 5s
      retries: 5

  opensearch:
    image: opensearchproject/opensearch:2.14.0
    environment:
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=admin123!
      - DISABLE_INSTALL_DEMO_CONFIG=true
      - discovery.type=single-node
      - plugins.security.disabled=true
      - OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health"]
      interval: 15s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile.dev
    env_file: ./apps/web/.env.local
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://app:app@postgres:5432/app
      - OPENSEARCH_URL=http://opensearch:9200
      - REDIS_URL=redis://redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      opensearch:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "3000:3000"
    volumes:
      # Mount the source code for hot reloading
      - ./apps/web/src:/app/apps/web/src
      - ./apps/web/public:/app/apps/web/public
      - ./apps/web/package.json:/app/apps/web/package.json
      - ./apps/web/next.config.js:/app/apps/web/next.config.js
      - ./apps/web/tsconfig.json:/app/apps/web/tsconfig.json
      - ./apps/web/prisma:/app/apps/web/prisma
      # Mount workspace files
      - ./package.json:/app/package.json
      - ./pnpm-workspace.yaml:/app/pnpm-workspace.yaml
      - ./pnpm-lock.yaml:/app/pnpm-lock.yaml
      # Mount shared package
      - ./packages/shared:/app/packages/shared

  ingestor:
    build: ./apps/ingestor
    env_file: ./apps/ingestor/.env.local
    depends_on:
      postgres:
        condition: service_healthy
      opensearch:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./data:/data

volumes:
  pgdata:
  opensearch_data:
